package game.integration_project1_zaroc.dao;

import java.io.IOException;
import java.io.InputStream;
import java.sql.*;
import java.util.Properties;

/**
 * Utility class providing commonly used methods for the DAO layer.
 * Handles connection creation, statement preparation and the creation/deletion of tables.
 * All methods use db.properties from the classpath to resolve
 * the database URL, username, and password.
 * This class is not meant to be instantiated.
 */
public class DaoUtils {

    /**
     * Loads the HSQLDB JDBC driver.
     *
     * @throws ZarocDaoException if the driver class cannot be found on the classpath
     */
    public static void loadDriver() throws ZarocDaoException {
        try {
            Class.forName("org.hsqldb.jdbcDriver");
        } catch (ClassNotFoundException e) {
            throw new ZarocDaoException("Fatal error: kan database driver niet laden", e);
        }
    }

    /**
     * Creates and returns a new database connection using values
     * loaded from db.properties
     *
     * @return an open connection to the database
     * @throws ZarocDaoException if the properties file is missing, cannot be read,
     *                           or the connection cannot be established
     */
    public static Connection createConnection() throws ZarocDaoException {
        Properties props = new Properties();

        try (InputStream input = DaoUtils.class
                .getClassLoader()
                .getResourceAsStream("db.properties")) {

            if (input == null) {
                throw new ZarocDaoException("db.properties file niet gevonden");
            }

            props.load(input);

            String url = props.getProperty("db.url");
            String user = props.getProperty("db.user");
            String password = props.getProperty("db.password");

            return DriverManager.getConnection(url, user, password);

        } catch (IOException e) {
            throw new ZarocDaoException("Error bij het lezen van db.properties", e);

        } catch (SQLException e) {
            throw new ZarocDaoException("Database connection gefaald", e);
        }
    }


    /**
     * Creates a {@link PreparedStatement} for the given SQL on the provided connection.
     *
     * @param connection the active database connection to use
     * @param sql        the SQL query to prepare
     * @return a prepared statement ready for values for the parameters and execution
     * @throws ZarocDaoException if the statement cannot be created
     */
    public static PreparedStatement createPreparedStatement(Connection connection, String sql) throws ZarocDaoException {
        try {
            return connection.prepareStatement(sql);
        } catch (SQLException e) {
            throw new ZarocDaoException("kan geen prepared statement maken", e);
        }
    }

        //Gebruik try with resources om automatisch alles af te sluiten (connection en statements)

    /**
     * Creates all database tables if they do not already exist.
     * PLAYERS, GAMES, GAME_PARTICIPATION, TURNS, MOVES, and GAME_ROOMS.
     *
     * @throws ZarocDaoException if the tables cannot be created because of a database error
     */
    public static void createTable() throws ZarocDaoException{
        String sql = """
                CREATE TABLE IF NOT EXISTS PLAYERS (
                                         player_id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 4),
                                         play_style VARCHAR(255),
                                         username VARCHAR(255) NOT NULL,
                                         email VARCHAR(255),
                                         difficulty VARCHAR(255),
                                         password VARCHAR(255),
                                         profile_picture VARCHAR(255),
                
                                         CONSTRAINT PK_PLAYER_ID PRIMARY KEY (player_id),
                                         CONSTRAINT CHK_PLAYER_DIFFICULTY CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD','ELITE')),
                                         CONSTRAINT CHK_PLAYER_PLAYSTYLE CHECK (play_style IN ('PASSIVE', 'AGGRESSIVE', 'DEFAULT'))
                );
                
                CREATE TABLE IF NOT EXISTS GAMES (
                                       game_id INT GENERATED ALWAYS AS IDENTITY,
                                       game_status VARCHAR(255) NOT NULL,
                                       start_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                
                                       CONSTRAINT PK_GAME_ID PRIMARY KEY (game_id)
                );
                
                CREATE TABLE IF NOT EXISTS GAME_PARTICIPATION (
                                                    player_id INT,
                                                    game_id INT,
                                                    pawn_color VARCHAR(255),
                                                    winner BOOLEAN,
                
                                                    CONSTRAINT PK_GAME_PARTICIPATION PRIMARY KEY (player_id, game_id),
                                                    CONSTRAINT FK_PARTICIPATION_PLAYER FOREIGN KEY (player_id) REFERENCES PLAYERS(player_id),
                                                    CONSTRAINT FK_PARTICIPATION_GAME FOREIGN KEY (game_id) REFERENCES GAMES(game_id)
                );
                
                CREATE TABLE IF NOT EXISTS TURNS (
                                       turn_id INT GENERATED ALWAYS AS IDENTITY,
                                       turn_number INTEGER NOT NULL,
                                       player_id INT,
                                       game_id INT,
                
                                       CONSTRAINT PK_TURN_ID PRIMARY KEY (turn_id),
                                       CONSTRAINT FK_TURN_PLAYER FOREIGN KEY (player_id) REFERENCES PLAYERS(player_id),
                                       CONSTRAINT FK_TURN_GAME FOREIGN KEY (game_id) REFERENCES GAMES(game_id)
                );
                
                CREATE TABLE IF NOT EXISTS MOVES (
                                       move_id INT GENERATED ALWAYS AS IDENTITY,
                                       move_number INTEGER NOT NULL,
                                       turn_id INT,
                                       start_time TIMESTAMP NOT NULL,
                                       end_time TIMESTAMP NOT NULL,
                                       start_location VARCHAR(255),
                                       end_location VARCHAR(255),
                
                                       CONSTRAINT PK_MOVE_ID PRIMARY KEY (move_id),
                                       CONSTRAINT FK_MOVE_TURN FOREIGN KEY (turn_id) REFERENCES TURNS(turn_id),
                                       CONSTRAINT CHK_MOVE_NUMBER CHECK (move_number IN (1, 2))
                );
                
                CREATE TABLE IF NOT EXISTS GAME_ROOMS (
                                                          room_id INT GENERATED ALWAYS AS IDENTITY,
                                                          room_code VARCHAR(10) NOT NULL,
                                                          host_id INT NOT NULL,
                                                          guest_id INT,
                                                          game_id INT,
                                                          status VARCHAR(50) DEFAULT 'WAITING',
                                                          host_color VARCHAR(20) DEFAULT 'BLACK',
                                                          guest_color VARCHAR(20) DEFAULT 'WHITE',
                
                                                          CONSTRAINT PK_ROOM_ID PRIMARY KEY (room_id),
                                                          CONSTRAINT UQ_ROOM_CODE UNIQUE (room_code),
                                                          CONSTRAINT FK_ROOM_HOST FOREIGN KEY (host_id) REFERENCES PLAYERS(player_id),
                                                          CONSTRAINT FK_ROOM_GUEST FOREIGN KEY (guest_id) REFERENCES PLAYERS(player_id),
                                                          CONSTRAINT FK_ROOM_GAME FOREIGN KEY (game_id) REFERENCES GAMES(game_id),
                                                          CONSTRAINT CHK_ROOM_STATUS CHECK (status IN ('WAITING', 'PLAYING', 'FINISHED'))
                );
                
                --Deze view berekent de outliers zelf , die wordt dan in een andere view gebruikt om te kijken welke moves er een outlier zijn
                CREATE OR REPLACE VIEW outliers AS
                SELECT move_id from moves
                WHERE extract(epoch FROM end_time) - extract(epoch from start_time) NOT BETWEEN (
                    SELECT
                        percentile_cont(0.25) WITHIN GROUP (ORDER BY extract(epoch FROM end_time) - extract(epoch from start_time)) - (1.5 * (percentile_cont(0.75) WITHIN GROUP (ORDER BY extract(epoch FROM end_time) - extract(epoch from start_time)) - (percentile_cont(0.25) WITHIN GROUP (ORDER BY extract(epoch FROM end_time) - extract(epoch from start_time))))) AS outlier_bottom
                    FROM moves
                    ) AND
                    (
                    SELECT
                        percentile_cont(0.75) WITHIN GROUP (ORDER BY extract(epoch FROM end_time) - extract(epoch from start_time)) + (1.5 * (percentile_cont(0.75) WITHIN GROUP (ORDER BY extract(epoch FROM end_time) - extract(epoch from start_time)) - (percentile_cont(0.25) WITHIN GROUP (ORDER BY extract(epoch FROM end_time) - extract(epoch from start_time))))) AS outlier_top
                    FROM moves
                    );
                
                CREATE OR REPLACE VIEW calculate_outliers AS
                SELECT p.username AS player,
                       g.start_time AS game,
                       CASE  -- Deze case bekijkt of de move van een winnende game participation is , indien ja zet hij W anders L
                           WHEN winner = true THEN 'W'
                           ELSE 'L'
                           END AS outcome,
                       m.start_time as move,
                       extract(epoch FROM m.end_time) - extract(epoch from m.start_time) AS duration, --dit berekent de duration tegenover EPOCH , aka 1 januari 1970
                       CASE -- Deze case zet een X wanneer de move voorkomt in de andere view, hij mag dus geen null waarde hebben bij de link want met de outer join komen die er ook bij
                           WHEN o.move_id IS NOT NULL THEN 'X'
                           ELSE ''
                           END AS outlier
                
                FROM moves m
                         JOIN turns t ON m.turn_id = t.turn_id
                         JOIN game_participation gp ON t.game_id = gp.game_id
                         JOIN games g ON gp.game_id = g.game_id
                         JOIN players p ON gp.player_id = p.player_id
                         LEFT JOIN outliers o ON m.move_id = o.move_id; --outer join op de view zodat we dus makkelijk kunnen controleren op een outlier
                
                
                """;

        try (Connection connection = DaoUtils.createConnection();
                PreparedStatement ps = DaoUtils.createPreparedStatement(connection, sql)) {
            ps.execute();
        } catch (SQLException e) {
            throw new ZarocDaoException("Er ging iets mis bij het maken van de tabellen in de db",e);
        }
    }

    public static void dropAllTables() throws SQLException, ZarocDaoException {

        String[] tables = {
                "MOVES",
                "TURNS",
                "GAME_PARTICIPATION",
                "GAMES",
                "PLAYERS",
                "GAME_ROOMS"
        };

        try (Connection conn = createConnection(); Statement stmt = conn.createStatement()) {
            for (String table : tables) {
                stmt.executeUpdate("DROP TABLE IF EXISTS " + table + " CASCADE");
            }
            System.out.println("Alle tabellen zijn succesvol verwijderd.");
        }
    }

}
