package game.integration_project1_zaroc.dao;

import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Properties;

public class DaoUtils {

    public static void loadDriver() throws ZarocDaoException {
        try {
            Class.forName("org.hsqldb.jdbcDriver");
        } catch (ClassNotFoundException e) {
            throw new ZarocDaoException("Fatal error: kan database driver niet laden", e);
        }
    }

    public static Connection createConnection() throws ZarocDaoException {
        Properties props = new Properties();

        try (InputStream input = DaoUtils.class
                .getClassLoader()
                .getResourceAsStream("db.properties")) {

            if (input == null) {
                throw new ZarocDaoException("db.properties file niet gevonden");
            }

            props.load(input);

            String url = props.getProperty("db.url");
            String user = props.getProperty("db.user");
            String password = props.getProperty("db.password");

            return DriverManager.getConnection(url, user, password);

        } catch (IOException e) {
            throw new ZarocDaoException("Error bij het lezen van db.properties", e);

        } catch (SQLException e) {
            throw new ZarocDaoException("Database connection gefaald", e);
        }
    }

    public static PreparedStatement createPreparedStatement(Connection connection, String sql) throws ZarocDaoException {
        try {
            return connection.prepareStatement(sql);
        } catch (SQLException e) {
            throw new ZarocDaoException("kan geen prepared statement maken", e);
        }
    }

        //Gebruik try with resources om automatisch alles af te sluiten (connection en statements)


    public static void createTable() throws ZarocDaoException{
        String sql = """
                CREATE TABLE PLAYERS (
                                         player_id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 4),
                                         play_style VARCHAR(255),
                                         username VARCHAR(255) NOT NULL,
                                         email VARCHAR(255),
                                         difficulty VARCHAR(255),
                                         password VARCHAR(255),
                                         profile_picture VARCHAR(255),
                
                                         CONSTRAINT PK_PLAYER_ID PRIMARY KEY (player_id),
                                         CONSTRAINT CHK_PLAYER_DIFFICULTY CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD')),
                                         CONSTRAINT CHK_PLAYER_PLAYSTYLE CHECK (play_style IN ('PASSIVE', 'AGGRESSIVE'))
                );
                
                CREATE TABLE GAMES (
                                       game_id INT GENERATED ALWAYS AS IDENTITY,
                                       game_status VARCHAR(255) NOT NULL,
                
                                       CONSTRAINT PK_GAME_ID PRIMARY KEY (game_id)
                );
                
                CREATE TABLE GAME_PARTICIPATION (
                                                    player_id INT,
                                                    game_id INT,
                                                    pawn_color VARCHAR(255),
                                                    winner_id INT,
                
                                                    CONSTRAINT PK_GAME_PARTICIPATION PRIMARY KEY (player_id, game_id),
                                                    CONSTRAINT FK_PARTICIPATION_PLAYER FOREIGN KEY (player_id) REFERENCES PLAYERS(player_id),
                                                    CONSTRAINT FK_PARTICIPATION_GAME FOREIGN KEY (game_id) REFERENCES GAMES(game_id),
                                                    CONSTRAINT FK_PARTICIPATION_WINNER FOREIGN KEY (winner_id) REFERENCES PLAYERS(player_id)
                );
                
                CREATE TABLE TURNS (
                                       turn_id INT GENERATED ALWAYS AS IDENTITY,
                                       turn_number INTEGER NOT NULL,
                                       player_id INT,
                                       game_id INT,
                
                                       CONSTRAINT PK_TURN_ID PRIMARY KEY (turn_id),
                                       CONSTRAINT FK_TURN_PLAYER FOREIGN KEY (player_id) REFERENCES PLAYERS(player_id),
                                       CONSTRAINT FK_TURN_GAME FOREIGN KEY (game_id) REFERENCES GAMES(game_id)
                );
                
                CREATE TABLE MOVES (
                                       move_id INT GENERATED ALWAYS AS IDENTITY,
                                       move_number INTEGER NOT NULL,
                                       turn_id INT,
                                       start_time TIMESTAMP NOT NULL,
                                       end_time TIMESTAMP NOT NULL,
                                       start_location VARCHAR(255),
                                       end_location VARCHAR(255),
                
                                       CONSTRAINT PK_MOVE_ID PRIMARY KEY (move_id),
                                       CONSTRAINT FK_MOVE_TURN FOREIGN KEY (turn_id) REFERENCES TURNS(turn_id),
                                       CONSTRAINT CHK_MOVE_NUMBER CHECK (move_number IN (1, 2))
                );""";

        try (Connection connection = DaoUtils.createConnection();
                PreparedStatement ps = DaoUtils.createPreparedStatement(connection, sql)) {
            ps.execute();
        } catch (SQLException e) {
            throw new ZarocDaoException("Er ging iets mis bij het maken van de tabellen in de db",e);
        }
    }

}
